---
# tasks file for php
  - name: install prerequis packages | Debian
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - lsb-release
      - ca-certificates
    when: ansible_distribution == "Debian"

  - name: ajout de la Key depot php7.2 | Debian
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      keyring: /etc/apt/trusted.gpg.d/php.gpg
      id: AC0E47584A7A714D
    when: ansible_distribution == "Debian"

  - name: ajout URL depot php7.2 | Debian
    apt_repository:
      repo: deb https://packages.sury.org/php/ stretch main
      state: present
    when: ansible_distribution == "Debian"
     
  - name: Install Packages PHP7.2 | Debian
    apt: name={{ item }} state=present
    with_items:
        - php7.2
        - php7.2-fpm
        - php7.2-mysql
        - php7.2-gd
        - php7.2-json
        - php7.2-curl
        - php7.2-mbstring
        - php7.2-xml
    when: ansible_distribution == "Debian"
  
  - name: Init Epel Repos | CentOS
    yum:
      name: epel-release
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Remi Repo | CentOS
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
    when: ansible_distribution == "CentOS"

  - name: Install yum-utils packages | CentOS
    yum:
      name: yum-utils
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Packages PHP7.2 | CentOS
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - php72
      - php72-php-fpm
      - php72-php-gd
      - php72-php-json
      - php72-php-mbstring
      - php72-php-mysqlnd
      - php72-php-xml
      - php72-php-xmlrpc
      - php72-php-opcache
    when: ansible_distribution == "CentOS"

  - name: Enable and start php | CentOS
    command: "{{ item }}"
    with_items:
      - systemctl enable php72-php-fpm.service
      - systemctl start php72-php-fpm.service
    when: ansible_distribution == "CentOS"

